---
# This is a role for setting up the server.

- name: Add user 1 and set password
  user:
    name: '{{ username_1 }}'
    password: '{{ password_1 | password_hash(''sha512'') }}'
    shell: '/bin/bash'


- name: Add user 2 and set password
  user:
    name: '{{ username_2 }}'
    password: '{{ password_2 | password_hash(''sha512'') }}'
    shell: '/bin/bash'

# - name: Install packages
#   apt:
#     pkg:
#      - telnetd
#     update_cache: yes

# - name: Change Telnet port
#   replace:
#     path: /etc/services
#     regexp: '23/tcp'
#     replace: '{{ telnet_port }}/tcp'

# xinetd must be installed after changing the Telnet port
# - name: Install xinetd package
#   apt:
#     name: xinetd


- name: Flag content
  copy:
    dest: '/home/{{ username_1 }}/flag.txt'
    owner: '{{ username_1 }}'
    content: "{{ flag }}\n"
    mode: '0666'

- name: Second user password
  copy:
    dest: '/home/{{ username_1 }}/user_2_password.txt'
    owner: '{{ username_1 }}'
    content: "{{ password_2 }}\n"
    mode: '0666'

- name: Test adding dynamic conent
  copy:
    dest: '/home/{{ username_1 }}/all_generated.txt'
    owner: '{{ username_1 }}'
    content: "{{ fake_flag }}\n{{ fake_flag_2 }}\n{{ random_password_1 }}\n{{ random_password_2 }}\n{{ random_text }}\n{{ random_username }}\n"
    mode: '0666'


- name: Create privilege escalation vulnerability
  lineinfile:
    path: /etc/sudoers
    line: '{{ username_2 }} ALL=(ALL) NOPASSWD: /usr/bin/less'


# - name: Create alias for client
#   lineinfile:
#     path: '/etc/hosts'
#     line: '192.168.30.5 client'
...
